# Generated by Django 4.1.2 on 2022-10-27 04:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Curiosityimages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "curiosity_images",
                    models.ImageField(blank=True, null=True, upload_to="media/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Essentialimages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "essential_images",
                    models.ImageField(blank=True, null=True, upload_to="media/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Premiumimages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "premium_images",
                    models.ImageField(blank=True, null=True, upload_to="media/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Productpackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("package_title", models.CharField(max_length=100)),
                ("package_category", models.CharField(max_length=100)),
                ("package_newprice", models.PositiveIntegerField()),
                ("package_oldprice", models.PositiveIntegerField()),
                ("package_description", models.CharField(max_length=1000)),
                (
                    "Package_points",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=1000),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "home_images",
                    models.ImageField(blank=True, null=True, upload_to="media/"),
                ),
                (
                    "inclusion_points",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=5000),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "turn_around_time",
                    models.CharField(
                        blank=True,
                        choices=[("6-7 weeks", "6-7 weeks")],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "sample_required",
                    models.CharField(
                        blank=True, choices=[("st", "Stool")], max_length=100, null=True
                    ),
                ),
                (
                    "sample_collection",
                    models.CharField(
                        blank=True,
                        choices=[("home", "At Home")],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "fasting_required",
                    models.CharField(
                        blank=True,
                        choices=[("n", "No"), ("y", "yes")],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "addon_name",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "addon_description",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "addon_price",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.PositiveIntegerField(),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
            ],
        ),
    ]
