# Generated by Django 4.1.2 on 2022-10-24 13:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpackage',
            name='package_images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.ImageField(upload_to='media'), blank=True, null=True, size=None),
        ),
    ]
