# Generated by Django 4.1.2 on 2022-10-27 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mbapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Packageimages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_images",
                    models.ImageField(blank=True, null=True, upload_to="media/"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mbapp.productpackage",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Curiosityimages",
        ),
        migrations.DeleteModel(
            name="Essentialimages",
        ),
        migrations.DeleteModel(
            name="Premiumimages",
        ),
    ]
