# Generated by Django 4.1.2 on 2022-10-21 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mbapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="package",
            name="images",
        ),
    ]
