# Generated by Django 4.1.2 on 2022-10-21 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mbapp", "0002_remove_package_images"),
    ]

    operations = [
        migrations.CreateModel(
            name="Homeimages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("home_images", models.ImageField(upload_to="media")),
            ],
        ),
    ]
