# Generated by Django 4.1.2 on 2022-10-25 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbapp', '0002_productpackage_package_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productpackage',
            name='package_images',
        ),
        migrations.AddField(
            model_name='productpackage',
            name='home_images',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
