# Generated by Django 4.1.2 on 2022-10-25 10:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbapp', '0004_curiosityimages_essentialimages_premiumimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpackage',
            name='inclusion_points',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=5000), blank=True, null=True, size=None),
        ),
    ]
