# Generated by Django 4.1.2 on 2022-10-25 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbapp', '0005_productpackage_inclusion_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpackage',
            name='fasting_required',
            field=models.CharField(blank=True, choices=[('n', 'No'), ('y', 'yes')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productpackage',
            name='sample_collection',
            field=models.CharField(blank=True, choices=[('home', 'At Home')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productpackage',
            name='sample_required',
            field=models.CharField(blank=True, choices=[('st', 'Stool')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productpackage',
            name='turn_around_time',
            field=models.CharField(blank=True, choices=[('1', '6-7 weeks')], max_length=100, null=True),
        ),
    ]
