# Generated by Django 4.1.2 on 2022-10-25 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbapp', '0006_productpackage_fasting_required_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpackage',
            name='turn_around_time',
            field=models.CharField(blank=True, choices=[('6-7 weeks', '6-7 weeks')], max_length=100, null=True),
        ),
    ]
